// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ApiEdilErreApp.Models;

[Keyless]
public partial class APPVistaSlot
{
    public int APP_IdSlot { get; set; }

    public int? APP_IdTipoSlot { get; set; }

    public int? APP_IdOperatore { get; set; }

    public int? APP_IdCantiere { get; set; }

    public int? APP_IdMacroFase { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? APP_DataSlot { get; set; }

    public int? APP_ViaggiDiscarica { get; set; }

    public int? App_ViaggiMateriali { get; set; }

    [StringLength(10)]
    public string APP_CodiceTipoSlot { get; set; }

    [StringLength(50)]
    public string APP_DescrizioneTipoSlot { get; set; }

    [StringLength(50)]
    public string APP_CognomeOperatore { get; set; }

    [StringLength(50)]
    public string APP_NomePeratore { get; set; }

    [StringLength(50)]
    public string DenominazioneCantiere { get; set; }

    public int? OrdinaleCantiereMacroFase { get; set; }

    [StringLength(10)]
    public string CodiceCantiereMacroFase { get; set; }

    [StringLength(50)]
    public string DescrizioneCantiereMacroFase { get; set; }
}