// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ApiEdilErreApp.Models;

[Keyless]
public partial class APPVistaSlotAutomezzi
{
    public int APP_IdAutomezzo { get; set; }

    public int APP_IdSlot { get; set; }

    public int IdAutoMezzo { get; set; }

    [StringLength(50)]
    public string Targa { get; set; }

    [StringLength(100)]
    public string DescrizioneMezzo { get; set; }
}