// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace ApiCampiAgricoli.Models;

public partial class CampiAgricoliContext : DbContext
{
    public CampiAgricoliContext()
    {
    }

    public CampiAgricoliContext(DbContextOptions<CampiAgricoliContext> options)
        : base(options)
    {
    }

    public virtual DbSet<TabCampi> TabCampi { get; set; }

    public virtual DbSet<TabMicrocontrollori> TabMicrocontrollori { get; set; }

    public virtual DbSet<TabMisurazioni> TabMisurazioni { get; set; }

    public virtual DbSet<TabSensori> TabSensori { get; set; }

    public virtual DbSet<TabSensoriTipologie> TabSensoriTipologie { get; set; }

    public virtual DbSet<TabUtenti> TabUtenti { get; set; }

    public virtual DbSet<VistaMicrocontrolloriUtente> VistaMicrocontrolloriUtente { get; set; }

    public virtual DbSet<VistaMisurazioniCampi> VistaMisurazioniCampi { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
        => optionsBuilder.UseSqlServer("Data Source=192.168.1.221,1433;Initial Catalog=CampiAgricoli;Persist Security Info=True;User ID=sa;Password=rootBase100;Encrypt=True;TrustServerCertificate=True");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<VistaMicrocontrolloriUtente>(entity =>
        {
            entity.ToView("VistaMicrocontrolloriUtente");
        });

        modelBuilder.Entity<VistaMisurazioniCampi>(entity =>
        {
            entity.ToView("VistaMisurazioniCampi");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}