// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ApiEdilErreApp.Models;

public partial class TabAPP_Operatori
{
    [Key]
    public int APP_IdOperatore { get; set; }

    [StringLength(50)]
    public string APP_CognomeOperatore { get; set; }

    [StringLength(50)]
    public string APP_NomePeratore { get; set; }

    [StringLength(50)]
    public string APP_Uid { get; set; }

    [StringLength(50)]
    public string APP_Pwd { get; set; }

    public int? APP_TipoOperatore { get; set; }

    public short? APP_FlagAbilitato { get; set; }
}