// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ApiEdilErreApp.Models;

public partial class TabAPP_TipoSlot
{
    [Key]
    public int APP_IdTipoSlot { get; set; }

    [StringLength(10)]
    public string APP_CodiceTipoSlot { get; set; }

    [StringLength(50)]
    public string APP_DescrizioneTipoSlot { get; set; }
}