// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ApiEdilErreApp.Models;

public partial class TabAPP_Automezzi
{
    [Key]
    public int APP_IdAutomezzo { get; set; }

    public int? APP_IdSlot { get; set; }

    public int? IdAutoMezzo { get; set; }
}