// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ApiEdilErreApp.Models;

public partial class TabAPP_Slots
{
    [Key]
    public int APP_IdSlot { get; set; }

    public int? APP_IdTipoSlot { get; set; }

    public int? APP_IdOperatore { get; set; }

    public int? APP_IdCantiere { get; set; }

    public int? APP_IdMacroFase { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? APP_DataSlot { get; set; }

    public int? APP_ViaggiDiscarica { get; set; }

    public int? App_ViaggiMateriali { get; set; }
}