// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ApiEdilErreApp.Models;

public partial class TabCantieriMacroFasi
{
    [Key]
    public int IdCantiereMacroFase { get; set; }

    public int? OrdinaleCantiereMacroFase { get; set; }

    [StringLength(10)]
    public string CodiceCantiereMacroFase { get; set; }

    [StringLength(50)]
    public string DescrizioneCantiereMacroFase { get; set; }
}