// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ApiEdilErreApp.Models;

public partial class TabCantieriFasi
{
    [Key]
    public int IdCantiereFase { get; set; }

    public int IdCantiereMacroFase { get; set; }

    public int? OrdinaleCantiereFase { get; set; }

    [StringLength(10)]
    public string CodiceCantiereFase { get; set; }

    [StringLength(50)]
    public string DescrizioneCantiereFase { get; set; }
}