// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ApiEdilErreApp.Models;

public partial class TabCantieri
{
    [Key]
    public int IdCantiere { get; set; }

    public int IdCantiereStato { get; set; }

    public int IdCantiereTipologia { get; set; }

    public int IdMondoCitta { get; set; }

    public int IdMondoNazione { get; set; }

    public int IdCommittente { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DataStatoCantiere { get; set; }

    [StringLength(10)]
    public string FMR_CodiceCantiere { get; set; }

    [StringLength(50)]
    public string DenominazioneCantiere { get; set; }

    [StringLength(128)]
    public string City { get; set; }

    [StringLength(128)]
    public string Localita { get; set; }

    [StringLength(128)]
    public string Nazione { get; set; }

    [StringLength(128)]
    public string ProvinciaStato { get; set; }

    [StringLength(50)]
    public string ZipCap { get; set; }

    [StringLength(128)]
    public string Indirizzo { get; set; }

    [StringLength(50)]
    public string NumeroCivico { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DataInizioLavori { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DataFineLavori { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DataUltimaNotifica { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? CostoCantiere { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? OneriSicurezzaCantiere { get; set; }

    [Column(TypeName = "decimal(18, 5)")]
    public decimal? MarkUpCantiere { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? PreventivoCantiere { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? TotaleFatturatoCantiere { get; set; }

    [StringLength(2048)]
    public string NoteCantiere { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? TotaleCostiPrestazioni { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? TotaleRicaviPrestazioni { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? TotaleCostiMateriali { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? TotaleRicaviMateriali { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? TotaleCostiServizi { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? TotaleRicaviServizi { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? TotaleCostiCantiere { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? TotaleRicaviCantiere { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? TotaleQuotaCostiGenerali { get; set; }
}