// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ApiCampiAgricoli.Models;

public partial class TabCampi
{
    [Key]
    public int IdCampo { get; set; }

    public int IdUtente { get; set; }

    [Required]
    [StringLength(50)]
    public string NomeCampo { get; set; }
}