// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ApiCampiAgricoli.Models;

public partial class TabMisurazioni
{
    [Key]
    public int IdMisurazione { get; set; }

    public int IdSensore { get; set; }

    public double? valoreMisurazione { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime dataOraCertaMisurazione { get; set; }
}