// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ApiCampiAgricoli.Models;

public partial class TabSensoriTipologie
{
    [Key]
    public int IdTipologiaSensore { get; set; }

    [Required]
    [StringLength(50)]
    public string DescrizioneTipologiaSensore { get; set; }
}