// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ApiCampiAgricoli.Models;

public partial class TabSensori
{
    [Key]
    public int IdSensore { get; set; }

    public int IdMicrocontrollore { get; set; }

    public int IdTipologiaSensore { get; set; }
}