// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ApiCampiAgricoli.Models;

public partial class TabUtenti
{
    [Key]
    public int IdUtente { get; set; }

    [Required]
    [StringLength(50)]
    public string NomeUtente { get; set; }

    [Required]
    [StringLength(50)]
    public string CognomeUtente { get; set; }

    [Required]
    [StringLength(50)]
    public string UsernameUtente { get; set; }

    [Required]
    [StringLength(50)]
    public string PasswordUtente { get; set; }

    [StringLength(50)]
    public string EmailUtente { get; set; }

    [StringLength(50)]
    public string TelefonoUtente { get; set; }
}